Update build-padavan.yml
使用旧的编译成功过的进行测试

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -9,7 +9,7 @@ on:
     branches: 
       - master
 #  schedule:
-#   - cron: 0 8 * * 5
+#    - cron: 0 8 * * 5
   watch:
     types: [started]
 
@@ -26,21 +26,31 @@ jobs:
         DEBIAN_FRONTEND: noninteractive
       run: |
         sudo apt update
-        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
-        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
-        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
-        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
-    - name: Clone source code and Build
+        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
+    - name: Clone source code
       run: |
-        git clone --depth=1 https://github.com/monw/rt-n56u.git /opt/rt-n56u
+        sudo git clone --depth=1 https://github.com/monw/rt-n56u.git /opt/rt-n56u
         cd /opt/rt-n56u/toolchain-mipsel
-        ./clean_toolchain
-        ./build_toolchain
+        sudo ./dl_toolchain.sh
+        sudo mkdir -p /opt/images/
+    - name: Build Firmware
+      env:
+        TNAME: R6220
+      run: |
         cd /opt/rt-n56u/trunk
-        fakeroot ./build_firmware_modify R6220
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
+        sudo ./clear_tree
+        sudo ./build_firmware_modify $TNAME
+        sudo mv -f images/*.trx /opt/images/
     - name : Upload packages
       uses: actions/upload-artifact@master
       if: always()
       with:
-        name: PadavanBuild
-        path: /opt/rt-n56u/trunk/images/*.trx
+        name: R6220—wifi-ok2222
+        path: /opt/images
