Update build-padavan.yml
在试试22

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -5,11 +5,11 @@ on:
     types: [published]
   push:
     tags:
-      - 'v*'
+    - 'v*'
     branches: 
       - master
-  # schedule:
-  #   - cron: 0 8 * * 5
+#  schedule:
+#    - cron: 0 8 * * 5
   watch:
     types: [started]
 
@@ -19,46 +19,38 @@ jobs:
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@master
-
-      - name: Initialization environment
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          sudo apt update
-          sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
-          cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
-          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
-
-      - name: Clone source code
-        run: |
-          sudo mkdir -p /opt/rt-n56u
-          sudo git clone --depth=1 https://github.com/monw/rt-n56u.git /opt/rt-n56u
-          cd /opt/rt-n56u/toolchain-mipsel
-          sudo ./dl_toolchain.sh
-          mkdir -p /opt/images/
-
-      - name: Build Firmware
-        env:
-          TNAME: R6220
-        run: |
-          cd /opt/rt-n56u/trunk
-          if [ ! -f configs/templates/$TNAME.config ] ; then
-            echo "ERROR: configs/templates/$TNAME.config not found "
-            exit 1
-          fi
-          cp -f configs/templates/$TNAME.config .config
-          sudo ./clear_tree
-          # 编译，失败直接终止
-          sudo ./build_firmware_modify $TNAME
-          # 查找固件，兼容不同输出目录
-          find . -name "*.trx" -exec mv {} /opt/images/ \;
-          ls -lh /opt/images/
-
-      - name: Upload packages
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: R6220-ok2222
-          path: /opt/images
+    - name: Checkout
+      uses: actions/checkout@master
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo apt update
+        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
+    - name: Clone source code
+      run: |
+        sudo git clone --depth=1 https://github.com/monw/rt-n56u.git /opt/rt-n56u
+        cd /opt/rt-n56u/toolchain-mipsel
+        sudo ./dl_toolchain.sh
+        sudo mkdir -p /opt/images/
+    - name: Build Firmware
+      env:
+        TNAME: R6220
+      run: |
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
+        sudo ./clear_tree
+        sudo ./build_firmware_modify $TNAME
+        sudo mv -f images/*.trx /opt/images/
+    - name: Upload packages
+      uses: actions/upload-artifact@master
+      if: always()
+      with:
+        name: R6220-ok222
+        path: ${{ github.workspace }}/opt/images
